apiVersion: v1
kind: Service
metadata:
  name: two-tier-flaskapp-service
spec:
  selector:
    app: two-tier-flaskapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30004
  type: NodePort
