apiVersion: v1
kind: Pod
metadata:
  name: two-tier-flaskapp-pod
spec:
  containers:
  - name: two-tier-flaskapp-pod
    image: salmansarwar/flask-app:latest
    env:
      - name: MYSQL_HOST
        value: "10.109.35.95"          # this is your mysql's service clusture IP, Make sure to change it with yours
      - name: MYSQL_PASSWORD
        value: "admin"
      - name: MYSQL_USER
        value: "root"
      - name: MYSQL_DB
        value: "mydb"
    ports:
      - containerPort: 5000
    imagePullPolicy: Always
    
